version: "3.7"
services:
  cloak-client:
    image: mohsenmottaghi/cloak-shadowsocks:cloak-client
    ports:
      - "12345:12345"
    environment:
      TRANSPORT:        direct
      METHOD:           shadowsocks
      ENCRYPTION:       plain
      CLIENTUID:        Wh0xJc4jNEevTqvmsWk9Yw==
      PUBLICKEY:        mDoo9XJVYjsh2nFe4RYrVYnd/kHyHMYD9RnDTtfR5VM=
      SERVERNAME:       example.com
      CONNECTIONNUM:    4
      BROWSER:          chrome
      SERVER_IP:        1.2.3.4
      LOCAL_PORT:       12345
      ADMINUID:         Wh0xJc4jNEevTqvmsWk9Yw==
    networks:
      - external
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: always

  shadowsocks-client:
    image: mohsenmottaghi/cloak-shadowsocks:shadowsocks-client
    ports:
      - "6060:6060"
    environment:
      SERVER_IP:     5.6.7.8
      SERVER_PORT:   12345
      LOCAL_IP:      0.0.0.0
      LOCAL_PORT:    6060
      ENCRYPTION:    AES-256-CFB
      PASSWORD:      password
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: always
        
networks:
  external:
  internal:
