version: "3.7"
services:
  cloak-server:
    image: mohsenmottaghi/cloak-shadowsocks:cloak-server
    ports:
      - "443:443"
    environment:
      LOCAL_IP:     ----- SERVER IP -----
      LOCAL_PORT:   8399
      METHOD:       shadowsocks
      BYPASSUID:    
      REDIRADDR:    1.0.0.1
      PRIVATEKEY:   
      ADMINUID:     
      DOMAIN:       example.com
    networks:
      - external
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: always

  shadowsocks-server:
    image: mohsenmottaghi/cloak-shadowsocks:shadowsocks-server
    ports:
      - "8399:8399"
    environment:
      SERVER_IP:     0.0.0.0
      SERVER_PORT:   8399
      ENCRYPTION:    AEAD_CHACHA20_POLY1305	
      PASSWORD:      password
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: always

networks:
  external:
  internal:
