version: "3.7"
services:
  cloak-server:
    image: TBD
    ports:
      - "443:443"
    environment:
      LOCAL_IP:     $LOCAL_IP
      LOCAL_PORT:   $LOCAL_PORT
      METHOD:       shadowsocks
      BYPASSUID:    $BYPASSUID
      REDIRADDR:    $REDIRADDR
      PRIVATEKEY:   $PRIVATEKEY
      ADMINUID:     $ADMINUID
      PUBLICKKEY:   $PUBLICKKEY
      ENCRYPTION:   $ENCRYPTION
      PASSWORD:     $PASSWORD
      DOMAIN:       example.com
      
    networks:
      - external
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: always

  shadowsocks-server:
    image: TBD
    ports:
      - "8399:8399"
    environment:
      SERVER_IP:     0.0.0.0
      SERVER_PORT:   $LOCAL_PORT
      ENCRYPTION:    $ENCRYPTION
      PASSWORD:      $PASSWORD
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: always

networks:
  external:
  internal:
